[OSPP][SD.cpp] add CLI params
WasmEdge/wasmedge-stable-diffusion pull request #9
Opened 2024-09-13 07:24 UTC by Tenderyi

Added command line input and modified the constructor in the rust file.

2024-09-13 07:30 UTC, hydai commented
Please fix the following two issues:
1. Do the DCO sign your commit; see https://wasmedge.org/docs/zh-tw/contribute/#dco
2. Please fix the conflicts in `rust/src/lib.rs`.

2024-09-16 09:47 UTC, hydai commented
Please run rustfmt and clippy to fix the coding style.

2024-09-18 15:11 UTC, hydai requested changes
Use `#[allow(clippy::too_many_arguments)]` to remove the too many arguments warnings.

2024-09-18 15:11 UTC, hydai commented on rust/src/lib.rs
> +//解析命令行参数，尤指 --mode
Please use English for writing comments.

2024-09-18 15:11 UTC, hydai commented on example/src/main.rs
> +        seed = ((rng.gen::<u32>() ^ current_time_secs) & i32::MAX as u32) as i32; // 将结果限制在 i32 范围内
Ditto.

2024-09-18 15:11 UTC, hydai commented
@apepkuss PTAL

2024-09-23 13:44 UTC, apepkuss requested changes

2024-09-23 13:44 UTC, apepkuss commented on rust/src/lib.rs
> +    ) -> &mut Self {
It would be better to use separate `set_xxx` functions to set each param instead of a all-in-one function. The reason is to keep each function to do a single and simple task only. Thanks!

2024-09-23 13:44 UTC, apepkuss commented on rust/src/lib.rs
> +            println!("self.common.prompt.is_empty()\n\n\n\n");
what's the purpose of this statement? If it is for debugging, please remove it. Thanks!

2024-09-25 22:02 UTC, hydai commented
This PR should be merged after https://github.com/WasmEdge/WasmEdge/pull/3763 gets merged. There is a strong relationship between the plugin and this binding.

2024-10-31 09:07 UTC, dm4 requested changes

2024-10-31 09:07 UTC, dm4 commented on rust/src/lib.rs
> +    pub fn new(model_path: &str, vae_model_path: String, output_path: &str, wtype: SdTypeT) -> Quantization {
CI failed. Need to run `rustfmt` formatter here.

2024-10-31 09:35 UTC, merged